### ISSUE TITLE
Dialyzer errors

### ISSUE THREAD

**Issue by suhrawardi** [sobolevn/ecto_autoslug_field#10]
Hi,

`slug.ex` is causing Dialyzer errors for me:

```
lib/ecto_autoslug_field/slug.ex:2: Function get_sources/2 has no local return
lib/ecto_autoslug_field/slug.ex:168: The pattern 'nil' can never match the type 'name'
```

Thanks!

**Comment by sobolevn** [comment]
Thanks! I would try to fix it.

I have actually never used `Dialyzer` myself. Any specific steps to reproduce this error? 
You may send a PR if you want to.

**Comment by suhrawardi** [comment]
Thanks for your prompt response.
Just add https://github.com/jeremyjh/dialyxir to a Phoenix project that uses an `ecto_autoslug_field`, and run:
`mix dialyzer`

Will have a look at it myself later too... 😃

**Comment by suhrawardi** [comment]
Please have a look at #11, any ideas?

**Comment by sobolevn** [comment]
@suhrawardi any feedback on this one? does it work?

**Comment by suhrawardi** [comment]
I'm afraid that it does not fix it.... :-(
Added the errors to my `.dialyzer/ignore-warnings` file...

**Comment by sobolevn** [comment]
I hope I have fix it at last:

> » mix dialyzer      
> Compiling 4 files (.ex)
> Generated ecto_autoslug_field app
> Checking PLT...
> [:ecto, :elixir, :ex_doc, :kernel, :logger, :slugger, :stdlib]
> PLT is up to date!
> Starting Dialyzer
> dialyzer args: [check_plt: false,
>  init_plt: '/Users/sobolev/Documents/github/ecto_autoslug_field/_build/dev/dialyxir_erlang-19.3_elixir-1.4.4_deps-dev.plt',
>  files_rec: ['/Users/sobolev/Documents/github/ecto_autoslug_field/_build/dev/lib/ecto_autoslug_field/ebin'],
>  warnings: [:unknown]]
> done in 0m1.77s
> done (passed successfully)

New version is coming.
