### ISSUE TITLE
Help with getting it to insert?

### ISSUE THREAD

**Issue by blcksheep80** [sobolevn/ecto_autoslug_field#104]
Hi,

I've been attempting to apply the tutorials to the following project: https://github.com/blcksheep80/blcksheepio-api

However, I can't seem to get the slug to generate? I created a field: https://github.com/blcksheep80/blcksheepio-api/blob/master/lib/blcksheepio_api/classification/fields/name_slug.ex

Which I've attempted to apply to https://github.com/blcksheep80/blcksheepio-api/blob/master/lib/blcksheepio_api/classification/category.ex

However, whenever I attempt to insert a new category I get the following back:

22:25:56.678 [info]  == Migrated 20190708054130 in 0.0s
[debug] QUERY ERROR db=1.0ms queue=1.4ms
INSERT INTO `categories` (`name`,`inserted_at`,`updated_at`,`id`) VALUES (?,?,?,?) ["delectus ab a qui eius", ~N[2019-10-16 19:25:57], ~N[2019-10-16 19:25:57], <<106, 124, 218, 218, 100, 235, 78, 227, 169, 137, 129, 200, 81, 162, 135, 94>>]
** (Mariaex.Error) (1364): Field 'slug' doesn't have a default value
    (ecto_sql) lib/ecto/adapters/mysql.ex:232: Ecto.Adapters.MySQL.insert/6
    (ecto) lib/ecto/repo/schema.ex:649: Ecto.Repo.Schema.apply/4
    (ecto) lib/ecto/repo/schema.ex:262: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
    (ecto) lib/ecto/repo/schema.ex:164: Ecto.Repo.Schema.insert!/4
    (elixir) lib/stream.ex:1341: Stream.do_repeatedly/3
    (elixir) lib/enum.ex:2486: Enum.take/2
    (blcksheepio_api) lib/mix/tasks/seed.ex:17: Mix.Tasks.BlcksheepIoApi.Seed.seed/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/task.ex:365: Mix.Task.run_alias/3
    (mix) lib/mix/task.ex:292: Mix.Task.run/2
    (mix) lib/mix/task.ex:365: Mix.Task.run_alias/3
    (mix) lib/mix/task.ex:292: Mix.Task.run/2
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
    (elixir) lib/code.ex:767: Code.require_file/2

**Comment by sobolevn** [comment]
Can you please do `|> IO.inspect` for the changeset here: https://github.com/blcksheep80/blcksheepio-api/blob/master/lib/blcksheepio_api/classification/category.ex#L25 and show me the output.
