### ISSUE TITLE
Two or most posts with same title

### ISSUE THREAD

**Issue by newterminator** [sobolevn/ecto_autoslug_field#13]
I wanted to ask that in implementing the unique constraint for lets say a post title to be converted to a slug, is it possible that if a title already exists with the same words/characters then while creating a new post, it adds random characters or numbers at the end to differentiate the post slugs.

In rails the [FriendlyId](https://github.com/norman/friendly_id) gem takes care of this. As an example I am posting images from a rails app using FriendlyId to create slugs from the post's title. 

<img width="733" alt="slug-post" src="https://cloud.githubusercontent.com/assets/5087437/26176930/ca829844-3b25-11e7-9d3b-ec94a43428d1.png">

Second post created with the same title:

<img width="854" alt="slug-post-unique-second" src="https://cloud.githubusercontent.com/assets/5087437/26176941/d304629a-3b25-11e7-87f0-2262ee908926.png">

Any help on this will be appreciated.

**Comment by sobolevn** [comment]
Thanks for your question! No, that's not implemented. 
How that's could be done:

```elixir
def build_slug(sources) do
    # Custom slug building rule:
    slug = super(source)
    if slug_exists(slug) do
      add_random_chars(slug)
    else
      slug
    end 
  end
```

Is that what you want?

**Comment by newterminator** [comment]
Hey @sobolevn , yes thats exactly what I was after ... When I added the above section and tried to implement the function add_random_chars(slug), the compiler gives an error saying `undefined function slug_exists/1`.

This is what I did:
```elixir
defmodule ComplexSlug do
  use EctoAutoslugField.Slug, from: :title, to: :slug

  def build_slug(sources) do
      # Custom slug building rule:
      slug = super(sources)
      if slug_exists(slug) do
        add_random_chars(slug)
      else
        slug
      end
  end

  def add_random_chars(slug) do
      slug = slug <> Base.url_encode64(slug)
  end
end

defmodule Myapp.Post do
  use Myapp.Web, :model
  
  @derive {Phoenix.Param, key: slug}
  schema "posts" do
      field :title, :string
      field :body, :string
      field :slug, ComplexSlug.Type
      ...
```

**Comment by sobolevn** [comment]
Sorry, did not make it clear: you have to write your own check for `slug_exists`.

**Comment by newterminator** [comment]
Awesome got it working. Thanks @sobolevn for writing this package for Ecto, and also for helping out with the issue.
