### ISSUE TITLE
Auto increment suffix of same slugs

### ISSUE THREAD

**Issue by ranyefet** [sobolevn/ecto_autoslug_field#15]
Hello,

Thanks for the great lib
In my use case the same slug can be generated. When that happens the unique constraint kicks in and fails the changeset.

I would like instead to try to insert the same entity with a auto incremented number

For example:
```elixir
changeset = Todo.changeset(Todo, %{text: "My Todo"})
todo = Repo.insert!(changeset)
```
Should return: 
```elixir
%Todo{text: "My Todo", slug: "my-todo"}
```

If I run the same insert again, I want to get back:
```elixir
%Todo{text: "My Todo", slug: "my-todo-2"}
```

Any tips on how to achieve that? 
Is this feature planned for this library?

Thanks,
Ran.

**Comment by sobolevn** [comment]
Thanks for your question and feedback!

 Will something like this work for you?

```elixir
defmodule TodoSlug do
  use EctoAutoslugField.Slug, from: :title, to: :slug

  def build_slug(sources) do
    # See docs:
    # https://hexdocs.pm/ecto_autoslug_field/EctoAutoslugField.SlugBase.html#build_slug/1
    slug = super(sources)  # => will receive default slug: my-todo

    # This code is just an example:
    current_todos_count = MyRepo.count_todos()
    slug <> "-" <> current_todos_count  # will set extra number: my-todo-4
  end
end

defmodule Todo do
  use Ecto.Schema

  schema "articles" do
    field :title, :string
    field :slug, TodoSlug.Type
  end
end
```

Please, take a note that `MyRepo.count_todos()` is just an example function.

**Comment by sobolevn** [comment]
And auto-incrementing suffixes out of the box is too hard to implement and maintain.

I like to pass it to the end developer.

**Comment by ranyefet** [comment]
I was not sure if it should be part of the library or not
Thanks @sobolevn it will work 👍

**Comment by ranyefet** [comment]
@sobolevn, when generating the slug I need to query the DB to check if the slug is already in use.
I can't query the DB in `build_slug` since I need more information from the `changeset`.

I looked at `get_sources` and it does accept the `changeset` but at that point I don't have the actual slug which I need to query the DB.

Any ideas?

**Comment by sobolevn** [comment]
Good point. Maybe we need to implement `build_slug(sources, changeset, opts)` as well?

**Comment by ranyefet** [comment]
Yeah, I don't see other way

**Comment by sobolevn** [comment]
Could you provide some more details? I would like to see your usecase to make a right design-decision.

**Comment by ranyefet** [comment]
Sure, let's say I have `Board` and `Todo` structs, which looks like:
```elixir
board = %Board{name: "My Board"}
todo = %Todo{board_id: "xxx", text: "My Todo"}
```

I want my todos URLs to be: `board/my-board/my-todo`
So my unique constraint is based on combination of board + todo.

Now, in the case someone tries to add a Todo item with the same text to the same board, the generated slug should be incremented to: `board/my-board/my-todo-2`

This is roughly what I try to accomplish:
```elixir
  def build_slug(sources, changeset) do
    slug = super(sources)
    build_unique_slug(slug, chanageset)
  end

  def build_unique_slug(slug, changeset) do
    board_id = chanageset.changes.board_id

    query = from t in Todo,
              where: t.board_id == ^board_id,
              where: t.slug == ^slug

    case Repo.one(query) do
      nil -> slug
      _todo -> 
        slug
        |> increment_slug
        |> build_unique_slug(changeset)
    end
  end
```

**Comment by ranyefet** [comment]
@sobolevn any updates?

**Comment by sobolevn** [comment]
I will have some time to work on it on weekends.

**Comment by ranyefet** [comment]
@sobolevn would it help if I submit a pull request?

**Comment by sobolevn** [comment]
It would be awesome!

**Comment by sobolevn** [comment]
I have made some changes to the project. Now `changeset` is fully optional.

I have removed hardcoded `&build_slug/2` function, now I am using a module `SlugBuilder` with multiple arities defined. I have also changed how `slug_builder` was invoked. It now uses this line:

`apply(SlugBuilder, :build_slug, [sources, changeset])`

I need to do some more testing before releasing it.

@ranyefet Do you have any feedback, please?

**Comment by ranyefet** [comment]
@sobolevn I've tested it with my code, and everything is still working, great work!

**Comment by sobolevn** [comment]
Nice, thanks again!
