### ISSUE TITLE
Forcing regenerating the slug on a particular record

### ISSUE THREAD

**Issue by nicolasblanco** [sobolevn/ecto_autoslug_field#30]
Hello,

Let's say I want to force the regeneration of a slug on a particular record without having to set globally the `always_change` option, what's the short way of doing that?
What do you think of having a function called `force_generate_slug`?

Thanks.

**Comment by sobolevn** [comment]
@nicolasblanco Thanks! I can totally see some usecases for that.

Do you want to contribute? PRs are more than welcomed.

**Comment by nicolasblanco** [comment]
@sobolevn : yes 👍.
Right now I'm just including this module in my slug modules:
https://gist.github.com/nicolasblanco/6a7d7a7784aec82e84d718f91eeb0edd

It basically adds a `force_generate_slug` function. It's just a quick copy/paste of `maybe_generate_slug` but it's always setting the option `always_change` before passing it...
Looks like it's doing what I want so far.

Maybe I will try to make a proper PR with some refactoring a bit later 😄.

**Comment by nicolasblanco** [comment]
https://github.com/sobolevn/ecto_autoslug_field/pull/31

**Comment by nicolasblanco** [comment]
Resolved in https://github.com/sobolevn/ecto_autoslug_field/pull/31
