### ISSUE TITLE
(ArgumentError) invalid or unknown type TitleSlug.Type

### ISSUE THREAD

**Issue by wernerlaude** [sobolevn/ecto_autoslug_field#36]
Following your tut, I only get: ** (ArgumentError) invalid or unknown type TitleSlug.Type for field :slug.
Any Idea?
Thanks

**Comment by sobolevn** [comment]
@wernerlaude could you please share your setup? 

How do you define your `schema`? What version of `ecto_autoslug_field` do you use?

**Comment by wernerlaude** [comment]
Hi Nikita..
this is what I have:

mix : {:ecto_autoslug_field, "~> 0.5"}

lib/MyApp/listings/meeting.ex:

defmodule MyApp.Listings.Meeting do
  use Ecto.Schema
  import Ecto.Changeset

  use EctoAutoslugField.Slug, from: :title, to: :slug

  schema "meetings" do
    field :title, :string
   ....
   field :slug, TitleSlug.Type


def changeset(meeting, attrs) do
    meeting
   .....
    |> unique_constraint(:title, name: :meetings_title_index)
    |> TitleSlug.maybe_generate_slug
    |> TitleSlug.unique_constraint
  end

and a migration in meetings ..slug
does it help?
Thanks for support.
Werner

**Comment by sobolevn** [comment]
@wernerlaude you are supposed to create a new module, something like this:

```elixir
# put this code in lib/MyApp/listings/meeting.ex
defmodule MyApp.Listings.Meeting.TitleSlug do
  use EctoAutoslugField.Slug, from: :title, to: :slug
end
```

And then use it:

```elixir
defmodule MyApp.Listings.Meeting do
  use Ecto.Schema
  import Ecto.Changeset
  alias MyApp.Listings.Meeting.TitleSlug

  schema do
     ...
     field :slug, TitleSlug.Type
  end
end
```

I hope this will help. Please, verify that this works.

**Comment by wernerlaude** [comment]
Yes , so far so good, was my fault..not reading properly..
